table order_details
	lineageTag: 3fec97e5-7a2a-40f9-bcd3-9cc4dd1cdd25

	column order_details_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c1d0bdf4-6507-4113-81cf-28c31f6092d1
		summarizeBy: none
		sourceColumn: order_details_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column order_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0f2daece-a47a-43a1-93b6-a2d7e8d9d079
		summarizeBy: none
		sourceColumn: order_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column pizza_id
		dataType: string
		isHidden
		lineageTag: 4b56153e-c055-485f-8618-a4730f3e31ff
		summarizeBy: none
		sourceColumn: pizza_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: 3c782f0c-6490-4fbc-96a2-196d5b2e414b
		summarizeBy: none
		sourceColumn: quantity

		annotation SummarizationSetBy = User

	partition order_details = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Jteja\Downloads\Pizza+Place+Sales\pizza_sales\order_details.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"order_details_id", Int64.Type}, {"order_id", Int64.Type}, {"pizza_id", type text}, {"quantity", Int64.Type}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Changed Type",{{"pizza_id", Text.Trim, type text}}),
				    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"pizza_id", Text.Clean, type text}})
				in
				    #"Cleaned Text"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

